package com.unibus.api.transport;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class JourneyTrackingServiceTests {

    private JdbcTemplate jdbcTemplate;
    private JourneyTrackingService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:journey-tracking;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("DROP ALL OBJECTS");
        jdbcTemplate.execute("CREATE TABLE routes (route_id INTEGER PRIMARY KEY, route_code VARCHAR(20), route_name VARCHAR(255), color_hex VARCHAR(20), status VARCHAR(20))");
        jdbcTemplate.execute("CREATE TABLE stops (stop_id INTEGER PRIMARY KEY, stop_name VARCHAR(255), address VARCHAR(255), latitude NUMERIC(12,8), longitude NUMERIC(12,8), status VARCHAR(20))");
        jdbcTemplate.execute("CREATE TABLE route_stops (route_id INTEGER, stop_id INTEGER, stop_order INTEGER, station_direction INTEGER, path_points VARCHAR(2000))");
        jdbcTemplate.execute("CREATE TABLE buses (bus_id INTEGER PRIMARY KEY, license_plate VARCHAR(30))");
        jdbcTemplate.execute("CREATE TABLE trips (trip_id INTEGER PRIMARY KEY, route_id INTEGER, bus_id INTEGER, service_date DATE, status VARCHAR(30))");
        jdbcTemplate.execute("CREATE TABLE vehicle_locations (vehicle_location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trip_id INTEGER, latitude NUMERIC(12,8), longitude NUMERIC(12,8), speed_kmh NUMERIC(8,2), occupancy INTEGER, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

        jdbcTemplate.update("INSERT INTO routes VALUES (12, '12', 'Tuyến 12', '#84cc16', 'ACTIVE')");
        jdbcTemplate.update("INSERT INTO stops VALUES (1, 'Trạm A', 'A', 16.00000000, 108.00000000, 'ACTIVE'), (2, 'Trạm B', 'B', 16.10000000, 108.10000000, 'ACTIVE')");
        jdbcTemplate.update("INSERT INTO route_stops VALUES (12, 1, 1, 0, NULL), (12, 2, 2, 0, NULL)");
        jdbcTemplate.update("INSERT INTO buses VALUES (1, '43B-00001'), (2, '43B-00002'), (3, '43B-00003')");
        jdbcTemplate.update("INSERT INTO trips VALUES (101, 12, 1, CURRENT_DATE, 'RUNNING'), (102, 12, 2, CURRENT_DATE, 'RUNNING'), (103, 12, 3, CURRENT_DATE, 'NOT_STARTED')");
        jdbcTemplate.update("INSERT INTO vehicle_locations(trip_id, latitude, longitude, speed_kmh, occupancy) VALUES (101, 16.01, 108.01, 25, 10), (102, 16.02, 108.02, 30, 15), (103, 16.03, 108.03, 20, 5)");

        service = new JourneyTrackingService(mock(JourneyPlannerService.class), jdbcTemplate);
    }

    @Test
    void routeSnapshotReturnsOnlyActualRunningVehicles() {
        var snapshot = service.routeSnapshot(12, 1, 2);

        assertThat(snapshot.vehicles())
                .extracting(vehicle -> vehicle.vehicleId())
                .containsExactly("trip-101", "trip-102");
        assertThat(snapshot.simulated()).isFalse();
    }
}
