export const currentTripMock = {
  tripId: 'ITER1-TRIP-01',
  routeName: 'ITER1 - Campus Loop',
  status: 'IN_PROGRESS',
  licensePlate: '43B-ITER1-01',
  driverName: 'Nguyen Minh Tai',
  conductorName: 'Tran Phu Xe',
  conductorPhone: '0901234567',
  dispatcherName: 'Le Dieu Phoi',
  dispatcherPhone: '0909988776',
  departedAt: '07:15',
  estimatedArrivalAt: '08:00',
  averageSpeed: 32,
  passengerCount: 28,
  capacity: 45,
  safetyScore: 98,
  alerts: 'Khong co canh bao',
  stops: [
    { id: 1, name: 'Ky tuc xa phia Dong', time: '07:15', status: 'passed' },
    { id: 2, name: 'Dai hoc Bach khoa', time: '07:26', status: 'passed' },
    { id: 3, name: 'Cau Rong', time: '07:38', status: 'current' },
    { id: 4, name: 'Dai hoc Kinh te', time: '07:50', status: 'upcoming' },
    { id: 5, name: 'Ben xe trung tam', time: '08:00', status: 'upcoming' },
  ],
};

export const recentTripMocks = [
  {
    travelHistoryId: 'mock-history-1',
    tripId: 'ITER1-TRIP-02',
    routeName: 'ITER1 - City Connector',
    serviceDate: new Date().toISOString(),
    boardingStopName: 'Dai hoc Bach khoa',
    alightingStopName: 'Ben xe trung tam',
    boardedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    alightedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    status: 'Hoan thanh',
  },
  {
    travelHistoryId: 'mock-history-2',
    tripId: 'ITER1-TRIP-03',
    routeName: 'ITER1 - Campus Loop',
    serviceDate: new Date(Date.now() - 86400000).toISOString(),
    boardingStopName: 'Ky tuc xa phia Dong',
    alightingStopName: 'Dai hoc Kinh te',
    boardedAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    alightedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'Hoan thanh',
  },
];
