export const currentTripMock = {
  tripId: 'ITER1-TRIP-01',
  routeName: 'ITER1 - Campus Loop',
  status: 'Đang vận hành',
  licensePlate: '43B-ITER1-01',
  driverName: 'Nguyễn Minh Tài',
  conductorName: 'Trần Phụ Xe',
  conductorPhone: '0901 234 567',
  departedAt: '07:15',
  estimatedArrivalAt: '08:00',
  averageSpeed: 32,
  passengerCount: 28,
  capacity: 45,
  safetyScore: 98,
  alerts: 'Không có cảnh báo',
  stops: [
    { id: 1, name: 'Ký túc xá phía Đông', time: '07:15', status: 'passed' },
    { id: 2, name: 'Đại học Bách khoa', time: '07:26', status: 'passed' },
    { id: 3, name: 'Cầu Rồng', time: '07:38', status: 'current' },
    { id: 4, name: 'Đại học Kinh tế', time: '07:50', status: 'upcoming' },
    { id: 5, name: 'Bến xe trung tâm', time: '08:00', status: 'upcoming' },
  ],
};

export const recentTripMocks = [
  {
    travelHistoryId: 'mock-history-1',
    tripId: 'ITER1-TRIP-02',
    routeName: 'ITER1 - City Connector',
    serviceDate: new Date().toISOString(),
    boardingStopName: 'Đại học Bách khoa',
    alightingStopName: 'Bến xe trung tâm',
    boardedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    alightedAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    status: 'Hoàn thành',
  },
  {
    travelHistoryId: 'mock-history-2',
    tripId: 'ITER1-TRIP-03',
    routeName: 'ITER1 - Campus Loop',
    serviceDate: new Date(Date.now() - 86400000).toISOString(),
    boardingStopName: 'Ký túc xá phía Đông',
    alightingStopName: 'Đại học Kinh tế',
    boardedAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    alightedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    status: 'Hoàn thành',
  },
];
