-- V13: Recreate verification_codes table (dropped in V6) for persistent OTP storage.
-- Also adds missing tables for SRS-compliant features: driver_ratings, fare_changes,
-- internal_messages workflow fields, complaints/violations status fields, soft-delete on stops,
-- and notification_campaigns for scheduled notifications.
--
-- All statements are idempotent (IF NOT EXISTS / DO blocks) so they are safe to re-run.

-- ============================================================================
-- 1. verification_codes (persistent OTP challenges, replaces in-memory store)
-- ============================================================================
CREATE TABLE IF NOT EXISTS verification_codes (
    verification_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT verification_codes_purpose_check
        CHECK (purpose IN ('REGISTRATION', 'PASSWORD_RESET'))
);
CREATE INDEX IF NOT EXISTS idx_verification_codes_email_purpose
    ON verification_codes (email, purpose);
CREATE INDEX IF NOT EXISTS idx_verification_codes_expires_at
    ON verification_codes (expires_at);

-- ============================================================================
-- 2. driver_ratings (REQ-STU-011 - rate driver after trip)
-- ============================================================================
CREATE TABLE IF NOT EXISTS driver_ratings (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL REFERENCES drivers(driver_id),
    student_user_id INTEGER NOT NULL REFERENCES users(user_id),
    trip_id INTEGER REFERENCES trips(trip_id),
    star_rating INTEGER NOT NULL CHECK (star_rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_driver_ratings_student_trip UNIQUE (student_user_id, trip_id)
);
CREATE INDEX IF NOT EXISTS idx_driver_ratings_driver_id ON driver_ratings (driver_id);

-- ============================================================================
-- 3. fare_changes (REQ-ADM-007 - fare adjustment history with effective date)
-- ============================================================================
CREATE TABLE IF NOT EXISTS fare_changes (
    fare_change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fare_id INTEGER NOT NULL REFERENCES fares(fare_id),
    route_id INTEGER REFERENCES routes(route_id),
    old_amount BIGINT,
    new_amount BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    adjusted_by_user_id INTEGER NOT NULL REFERENCES users(user_id),
    reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_fare_changes_fare_id ON fare_changes (fare_id);
CREATE INDEX IF NOT EXISTS idx_fare_changes_effective_from ON fare_changes (effective_from);

-- ============================================================================
-- 4. notification_campaigns (REQ-ADM-006 - scheduled notification batches)
-- ============================================================================
CREATE TABLE IF NOT EXISTS notification_campaigns (
    campaign_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    audience_role VARCHAR(30),
    route_id INTEGER REFERENCES routes(route_id),
    university_id INTEGER REFERENCES universities(university_id),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_by_user_id INTEGER NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_campaigns_status_check
        CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'CANCELLED', 'FAILED'))
);

-- ============================================================================
-- 5. complaints / violation_reports: ensure status + resolution columns exist
--    (some of these may already exist; all guards are idempotent)
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'status') THEN
        ALTER TABLE complaints ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'OPEN';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'resolution') THEN
        ALTER TABLE complaints ADD COLUMN resolution TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'resolved_by_user_id') THEN
        ALTER TABLE complaints ADD COLUMN resolved_by_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'resolved_at') THEN
        ALTER TABLE complaints ADD COLUMN resolved_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'submitted_by_user_id') THEN
        ALTER TABLE complaints ADD COLUMN submitted_by_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'category') THEN
        ALTER TABLE complaints ADD COLUMN category VARCHAR(50);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'subject') THEN
        ALTER TABLE complaints ADD COLUMN subject VARCHAR(255);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'description') THEN
        ALTER TABLE complaints ADD COLUMN description TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'complaints' AND column_name = 'created_at') THEN
        ALTER TABLE complaints ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'status') THEN
        ALTER TABLE violation_reports ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'REPORTED';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'action_taken') THEN
        ALTER TABLE violation_reports ADD COLUMN action_taken VARCHAR(255);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'reviewed_by_user_id') THEN
        ALTER TABLE violation_reports ADD COLUMN reviewed_by_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'reviewed_at') THEN
        ALTER TABLE violation_reports ADD COLUMN reviewed_at TIMESTAMPTZ;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'reported_by_user_id') THEN
        ALTER TABLE violation_reports ADD COLUMN reported_by_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'category') THEN
        ALTER TABLE violation_reports ADD COLUMN category VARCHAR(50);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'description') THEN
        ALTER TABLE violation_reports ADD COLUMN description TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'violation_reports' AND column_name = 'created_at') THEN
        ALTER TABLE violation_reports ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
    END IF;
END $$;

-- ============================================================================
-- 6. internal_messages: ensure columns for sender/recipient + read status exist
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'internal_messages' AND column_name = 'sender_user_id') THEN
        ALTER TABLE internal_messages ADD COLUMN sender_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'internal_messages' AND column_name = 'recipient_user_id') THEN
        ALTER TABLE internal_messages ADD COLUMN recipient_user_id INTEGER REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'internal_messages' AND column_name = 'body') THEN
        ALTER TABLE internal_messages ADD COLUMN body TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'internal_messages' AND column_name = 'sent_at') THEN
        ALTER TABLE internal_messages ADD COLUMN sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'internal_messages' AND column_name = 'read_at') THEN
        ALTER TABLE internal_messages ADD COLUMN read_at TIMESTAMPTZ;
    END IF;
END $$;

-- ============================================================================
-- 7. stops: add deleted_at for soft delete (REQ-CRD-008 AC2)
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'stops' AND column_name = 'deleted_at') THEN
        ALTER TABLE stops ADD COLUMN deleted_at TIMESTAMPTZ;
    END IF;
END $$;

-- ============================================================================
-- 8. fares: add pending_amount + pending_effective_from for staged fare changes
--    (REQ-ADM-007 AC1 "Giá mới hiệu lực sau 24h")
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'fares' AND column_name = 'pending_amount') THEN
        ALTER TABLE fares ADD COLUMN pending_amount BIGINT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'fares' AND column_name = 'pending_effective_from') THEN
        ALTER TABLE fares ADD COLUMN pending_effective_from DATE;
    END IF;
END $$;
