ALTER TABLE routes
    ADD COLUMN IF NOT EXISTS external_source VARCHAR(40),
    ADD COLUMN IF NOT EXISTS external_route_id VARCHAR(80),
    ADD COLUMN IF NOT EXISTS source_updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS is_interregional BOOLEAN DEFAULT false NOT NULL;

ALTER TABLE stops
    ADD COLUMN IF NOT EXISTS external_source VARCHAR(40),
    ADD COLUMN IF NOT EXISTS external_stop_id VARCHAR(80),
    ADD COLUMN IF NOT EXISTS source_updated_at TIMESTAMPTZ;

ALTER TABLE route_stops
    ADD COLUMN IF NOT EXISTS station_direction INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS path_points TEXT,
    ADD COLUMN IF NOT EXISTS distance_from_previous_m NUMERIC(10,2);

UPDATE route_stops
SET station_direction = 0
WHERE station_direction IS NULL;

ALTER TABLE route_stops
    DROP CONSTRAINT IF EXISTS uq_route_stops_order;

CREATE UNIQUE INDEX IF NOT EXISTS uq_route_stops_direction_order
    ON route_stops(route_id, station_direction, stop_order);

CREATE INDEX IF NOT EXISTS ix_routes_external_source_id
    ON routes(external_source, external_route_id);

CREATE INDEX IF NOT EXISTS ix_routes_interregional
    ON routes(is_interregional, status);

CREATE INDEX IF NOT EXISTS ix_stops_external_source_id
    ON stops(external_source, external_stop_id);

CREATE INDEX IF NOT EXISTS ix_stops_geo_active
    ON stops(status, latitude, longitude);

CREATE TABLE IF NOT EXISTS journey_orders (
    journey_order_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    origin_label VARCHAR(255) NOT NULL,
    destination_label VARCHAR(255) NOT NULL,
    total_amount NUMERIC(12,0) NOT NULL,
    subsidy_amount NUMERIC(12,0) DEFAULT 0 NOT NULL,
    final_amount NUMERIC(12,0) NOT NULL,
    qr_code VARCHAR(255) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    purchased_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_from DATE NOT NULL,
    expires_on DATE NOT NULL,
    CONSTRAINT pk_journey_orders PRIMARY KEY (journey_order_id),
    CONSTRAINT uq_journey_orders_qr_code UNIQUE (qr_code),
    CONSTRAINT ck_journey_orders_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS journey_order_items (
    journey_order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    journey_order_id INTEGER NOT NULL,
    monthly_pass_id INTEGER NOT NULL,
    route_id INTEGER NOT NULL,
    leg_order INTEGER NOT NULL,
    boarding_stop_id INTEGER,
    alighting_stop_id INTEGER,
    original_amount NUMERIC(12,0) NOT NULL,
    subsidy_amount NUMERIC(12,0) DEFAULT 0 NOT NULL,
    final_amount NUMERIC(12,0) NOT NULL,
    CONSTRAINT pk_journey_order_items PRIMARY KEY (journey_order_item_id),
    CONSTRAINT fk_journey_order_items_order FOREIGN KEY (journey_order_id) REFERENCES journey_orders(journey_order_id) ON DELETE CASCADE,
    CONSTRAINT fk_journey_order_items_monthly_pass FOREIGN KEY (monthly_pass_id) REFERENCES monthly_passes(monthly_pass_id),
    CONSTRAINT fk_journey_order_items_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
    CONSTRAINT fk_journey_order_items_boarding_stop FOREIGN KEY (boarding_stop_id) REFERENCES stops(stop_id),
    CONSTRAINT fk_journey_order_items_alighting_stop FOREIGN KEY (alighting_stop_id) REFERENCES stops(stop_id),
    CONSTRAINT uq_journey_order_items_leg UNIQUE (journey_order_id, leg_order)
);

CREATE INDEX IF NOT EXISTS ix_journey_orders_student_status
    ON journey_orders(student_code, status, purchased_at DESC);

CREATE INDEX IF NOT EXISTS ix_journey_order_items_route_pass
    ON journey_order_items(route_id, monthly_pass_id);
