CREATE TABLE IF NOT EXISTS verification_codes (
    verification_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                VARCHAR(100) NOT NULL,
    purpose              VARCHAR(20) NOT NULL
                         CHECK (purpose IN ('REGISTER', 'RESET_PASSWORD')),
    code_hash            VARCHAR(255) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at           TIMESTAMPTZ NOT NULL,
    consumed_at          TIMESTAMPTZ,
    attempt_count        INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT pk_verification_codes PRIMARY KEY (verification_code_id)
);

CREATE INDEX IF NOT EXISTS ix_verification_codes_active
    ON verification_codes(email, purpose, expires_at DESC)
    WHERE consumed_at IS NULL;
