ALTER TABLE users
    ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS student_verification_status VARCHAR(30) NOT NULL DEFAULT 'NOT_SUBMITTED';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_users_student_verification_status'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users
            ADD CONSTRAINT ck_users_student_verification_status
            CHECK (student_verification_status IN (
                'NOT_SUBMITTED',
                'PENDING_REVIEW',
                'VERIFIED',
                'REJECTED',
                'RESUBMISSION_REQUIRED'
            ));
    END IF;
END $$;

UPDATE users
SET email_verified_at = COALESCE(email_verified_at, created_at)
WHERE email_verified_at IS NULL;

UPDATE users u
SET student_verification_status = 'VERIFIED'
WHERE u.role = 'STUDENT'
  AND EXISTS (
      SELECT 1
      FROM students s
      WHERE s.user_id = u.user_id
  );

CREATE TABLE IF NOT EXISTS user_auth_providers (
    user_auth_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               INTEGER NOT NULL,
    provider              VARCHAR(30) NOT NULL,
    provider_user_id      VARCHAR(191) NOT NULL,
    provider_email        VARCHAR(100) NOT NULL,
    provider_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    display_name          VARCHAR(100),
    avatar_url            VARCHAR(500),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ,

    CONSTRAINT pk_user_auth_providers PRIMARY KEY (user_auth_provider_id),
    CONSTRAINT ck_user_auth_providers_provider CHECK (provider IN ('GOOGLE')),
    CONSTRAINT fk_user_auth_providers_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_user_auth_providers_provider_uid UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_user_auth_providers_user_provider UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS ix_user_auth_providers_user
    ON user_auth_providers(user_id);

CREATE TABLE IF NOT EXISTS student_verifications (
    student_verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 INTEGER NOT NULL,
    university              VARCHAR(150) NOT NULL,
    student_code            VARCHAR(20) NOT NULL,
    card_image_url          VARCHAR(500),
    ocr_full_name           VARCHAR(100),
    ocr_student_code        VARCHAR(20),
    ocr_university          VARCHAR(150),
    ocr_raw_text            TEXT,
    ocr_confidence_score    NUMERIC(5,4),
    status                  VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW',
    rejection_reason        VARCHAR(500),
    reviewer_user_id        INTEGER,
    reviewed_at             TIMESTAMPTZ,
    submitted_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ,
    is_current              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_student_verifications PRIMARY KEY (student_verification_id),
    CONSTRAINT ck_student_verifications_status CHECK (status IN (
        'NOT_SUBMITTED',
        'PENDING_REVIEW',
        'VERIFIED',
        'REJECTED',
        'RESUBMISSION_REQUIRED'
    )),
    CONSTRAINT ck_student_verifications_ocr_confidence
        CHECK (ocr_confidence_score IS NULL OR (ocr_confidence_score >= 0 AND ocr_confidence_score <= 1)),
    CONSTRAINT fk_student_verifications_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_student_verifications_reviewer FOREIGN KEY (reviewer_user_id)
        REFERENCES users(user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_user
    ON student_verifications(user_id)
    WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_student_code
    ON student_verifications(student_code)
    WHERE is_current AND status IN ('PENDING_REVIEW', 'VERIFIED', 'RESUBMISSION_REQUIRED');

CREATE INDEX IF NOT EXISTS ix_student_verifications_status
    ON student_verifications(status, submitted_at DESC);

INSERT INTO student_verifications (
    user_id,
    university,
    student_code,
    card_image_url,
    ocr_full_name,
    ocr_student_code,
    ocr_university,
    ocr_raw_text,
    ocr_confidence_score,
    status,
    reviewed_at,
    submitted_at,
    created_at,
    updated_at,
    is_current
)
SELECT
    s.user_id,
    s.university,
    s.student_code,
    NULL,
    u.full_name,
    s.student_code,
    s.university,
    'Imported from existing student profile during V3 migration',
    1,
    'VERIFIED',
    CURRENT_TIMESTAMP,
    COALESCE(u.created_at, CURRENT_TIMESTAMP),
    COALESCE(u.created_at, CURRENT_TIMESTAMP),
    CURRENT_TIMESTAMP,
    TRUE
FROM students s
JOIN users u ON u.user_id = s.user_id
WHERE NOT EXISTS (
    SELECT 1
    FROM student_verifications sv
    WHERE sv.user_id = s.user_id
      AND sv.is_current
);
