DO $$ 
BEGIN 
    BEGIN ALTER TABLE bus_schedules ALTER COLUMN bus_id DROP NOT NULL; EXCEPTION WHEN OTHERS THEN END;
    BEGIN ALTER TABLE bus_schedules ALTER COLUMN driver_staff_id DROP NOT NULL; EXCEPTION WHEN OTHERS THEN END;
    BEGIN ALTER TABLE bus_schedules ALTER COLUMN driver_id DROP NOT NULL; EXCEPTION WHEN OTHERS THEN END;
    BEGIN ALTER TABLE bus_schedules ALTER COLUMN conductor_staff_id DROP NOT NULL; EXCEPTION WHEN OTHERS THEN END;
    BEGIN ALTER TABLE bus_schedules ALTER COLUMN conductor_id DROP NOT NULL; EXCEPTION WHEN OTHERS THEN END;
END $$;
