CREATE TABLE IF NOT EXISTS universities (
    university_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    short_name VARCHAR(80),
    contact_email VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_universities PRIMARY KEY (university_id),
    CONSTRAINT uq_universities_code UNIQUE (code),
    CONSTRAINT uq_universities_name UNIQUE (name),
    CONSTRAINT ck_universities_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS campuses (
    campus_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    latitude NUMERIC(10,8),
    longitude NUMERIC(11,8),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_campuses PRIMARY KEY (campus_id),
    CONSTRAINT uq_campuses_university_code UNIQUE (university_id, code),
    CONSTRAINT ck_campuses_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS route_universities (
    route_university_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id INTEGER NOT NULL,
    university_id INTEGER NOT NULL,
    campus_id INTEGER,
    active_from DATE DEFAULT CURRENT_DATE NOT NULL,
    active_until DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_route_universities PRIMARY KEY (route_university_id),
    CONSTRAINT ck_route_universities_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_route_universities_dates CHECK (active_until IS NULL OR active_until >= active_from)
);

CREATE TABLE IF NOT EXISTS subsidy_policies (
    subsidy_policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    campus_id INTEGER,
    policy_name VARCHAR(150) NOT NULL,
    subsidy_type VARCHAR(20) NOT NULL,
    "value" NUMERIC(12,2) NOT NULL,
    max_amount NUMERIC(12,0),
    active_from DATE DEFAULT CURRENT_DATE NOT NULL,
    active_until DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_subsidy_policies PRIMARY KEY (subsidy_policy_id),
    CONSTRAINT ck_subsidy_policies_type CHECK (subsidy_type IN ('PERCENTAGE', 'FIXED_AMOUNT')),
    CONSTRAINT ck_subsidy_policies_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_subsidy_policies_value CHECK ("value" >= 0),
    CONSTRAINT ck_subsidy_policies_max CHECK (max_amount IS NULL OR max_amount >= 0),
    CONSTRAINT ck_subsidy_policies_dates CHECK (active_until IS NULL OR active_until >= active_from)
);

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS university_id INTEGER;

ALTER TABLE student_verifications
    ADD COLUMN IF NOT EXISTS university_id INTEGER;

ALTER TABLE monthly_passes
    ADD COLUMN IF NOT EXISTS original_fare_amount NUMERIC(12,0),
    ADD COLUMN IF NOT EXISTS subsidy_amount NUMERIC(12,0),
    ADD COLUMN IF NOT EXISTS final_fare_amount NUMERIC(12,0),
    ADD COLUMN IF NOT EXISTS subsidy_policy_id INTEGER;

ALTER TABLE invoices
    ADD COLUMN IF NOT EXISTS original_amount NUMERIC(12,0),
    ADD COLUMN IF NOT EXISTS subsidy_amount NUMERIC(12,0),
    ADD COLUMN IF NOT EXISTS final_amount NUMERIC(12,0);

INSERT INTO universities (code, name, short_name, status)
SELECT 'UNI-' || substr(md5(name), 1, 8), name, left(name, 80), 'ACTIVE'
FROM (
    SELECT DISTINCT trim(university) AS name
    FROM students
    WHERE university IS NOT NULL AND trim(university) <> ''
    UNION
    SELECT DISTINCT trim(university) AS name
    FROM student_verifications
    WHERE university IS NOT NULL AND trim(university) <> ''
) source
ON CONFLICT (name) DO NOTHING;

UPDATE students s
SET university_id = u.university_id
FROM universities u
WHERE s.university_id IS NULL
  AND lower(trim(s.university)) = lower(trim(u.name));

UPDATE student_verifications sv
SET university_id = u.university_id
FROM universities u
WHERE sv.university_id IS NULL
  AND lower(trim(sv.university)) = lower(trim(u.name));

UPDATE monthly_passes
SET original_fare_amount = COALESCE(original_fare_amount, fare_amount),
    subsidy_amount = COALESCE(subsidy_amount, 0),
    final_fare_amount = COALESCE(final_fare_amount, fare_amount)
WHERE original_fare_amount IS NULL
   OR subsidy_amount IS NULL
   OR final_fare_amount IS NULL;

UPDATE invoices
SET original_amount = COALESCE(original_amount, amount),
    subsidy_amount = COALESCE(subsidy_amount, 0),
    final_amount = COALESCE(final_amount, amount)
WHERE original_amount IS NULL
   OR subsidy_amount IS NULL
   OR final_amount IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_campuses_university' AND conrelid = 'campuses'::regclass) THEN
        ALTER TABLE campuses ADD CONSTRAINT fk_campuses_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_universities_route' AND conrelid = 'route_universities'::regclass) THEN
        ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_universities_university' AND conrelid = 'route_universities'::regclass) THEN
        ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_route_universities_campus' AND conrelid = 'route_universities'::regclass) THEN
        ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_campus FOREIGN KEY (campus_id) REFERENCES campuses(campus_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subsidy_policies_university' AND conrelid = 'subsidy_policies'::regclass) THEN
        ALTER TABLE subsidy_policies ADD CONSTRAINT fk_subsidy_policies_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subsidy_policies_campus' AND conrelid = 'subsidy_policies'::regclass) THEN
        ALTER TABLE subsidy_policies ADD CONSTRAINT fk_subsidy_policies_campus FOREIGN KEY (campus_id) REFERENCES campuses(campus_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_students_university' AND conrelid = 'students'::regclass) THEN
        ALTER TABLE students ADD CONSTRAINT fk_students_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_student_verifications_university' AND conrelid = 'student_verifications'::regclass) THEN
        ALTER TABLE student_verifications ADD CONSTRAINT fk_student_verifications_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_monthly_passes_subsidy_policy' AND conrelid = 'monthly_passes'::regclass) THEN
        ALTER TABLE monthly_passes ADD CONSTRAINT fk_monthly_passes_subsidy_policy FOREIGN KEY (subsidy_policy_id) REFERENCES subsidy_policies(subsidy_policy_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_students_university
    ON students(university_id);

CREATE INDEX IF NOT EXISTS ix_student_verifications_university
    ON student_verifications(university_id);

CREATE INDEX IF NOT EXISTS ix_route_universities_lookup
    ON route_universities(university_id, route_id, status, active_from, active_until);

CREATE INDEX IF NOT EXISTS ix_subsidy_policies_lookup
    ON subsidy_policies(university_id, status, active_from, active_until);
