ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users
    ADD CONSTRAINT users_role_check
    CHECK (role IN ('STUDENT', 'DRIVER', 'CONDUCTOR', 'DISPATCHER', 'UNIVERSITY_ADMIN', 'ADMIN'));

CREATE TABLE IF NOT EXISTS university_domains (
    university_domain_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    domain VARCHAR(120) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_domains PRIMARY KEY (university_domain_id),
    CONSTRAINT uq_university_domains_domain UNIQUE (domain),
    CONSTRAINT ck_university_domains_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS university_admins (
    university_admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    title VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by_user_id INTEGER,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_admins PRIMARY KEY (university_admin_id),
    CONSTRAINT uq_university_admins_user UNIQUE (user_id),
    CONSTRAINT ck_university_admins_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS university_student_rosters (
    roster_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    faculty VARCHAR(100),
    academic_year INTEGER,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    matched_user_id INTEGER,
    imported_batch_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_student_rosters PRIMARY KEY (roster_id),
    CONSTRAINT uq_university_roster_email UNIQUE (university_id, email),
    CONSTRAINT uq_university_roster_student_code UNIQUE (university_id, student_code),
    CONSTRAINT ck_university_rosters_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'GRADUATED', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS university_import_batches (
    import_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    total_rows INTEGER DEFAULT 0 NOT NULL,
    success_rows INTEGER DEFAULT 0 NOT NULL,
    error_rows INTEGER DEFAULT 0 NOT NULL,
    status VARCHAR(30) DEFAULT 'PROCESSING' NOT NULL,
    imported_by_user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT pk_university_import_batches PRIMARY KEY (import_batch_id),
    CONSTRAINT ck_university_import_batches_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS university_import_errors (
    import_error_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    import_batch_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(80),
    raw_value TEXT,
    error_message VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_university_import_errors PRIMARY KEY (import_error_id)
);

ALTER TABLE audit_logs
    ADD COLUMN IF NOT EXISTS university_id INTEGER,
    ADD COLUMN IF NOT EXISTS result VARCHAR(30),
    ADD COLUMN IF NOT EXISTS request_id VARCHAR(80);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_domains_university' AND conrelid = 'university_domains'::regclass) THEN
        ALTER TABLE university_domains ADD CONSTRAINT fk_university_domains_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_admins_university' AND conrelid = 'university_admins'::regclass) THEN
        ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_admins_user' AND conrelid = 'university_admins'::regclass) THEN
        ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_user FOREIGN KEY (user_id) REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_admins_assigned_by' AND conrelid = 'university_admins'::regclass) THEN
        ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_rosters_university' AND conrelid = 'university_student_rosters'::regclass) THEN
        ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_rosters_user' AND conrelid = 'university_student_rosters'::regclass) THEN
        ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_user FOREIGN KEY (matched_user_id) REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_rosters_batch' AND conrelid = 'university_student_rosters'::regclass) THEN
        ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_batch FOREIGN KEY (imported_batch_id) REFERENCES university_import_batches(import_batch_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_import_batches_university' AND conrelid = 'university_import_batches'::regclass) THEN
        ALTER TABLE university_import_batches ADD CONSTRAINT fk_university_import_batches_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_import_batches_user' AND conrelid = 'university_import_batches'::regclass) THEN
        ALTER TABLE university_import_batches ADD CONSTRAINT fk_university_import_batches_user FOREIGN KEY (imported_by_user_id) REFERENCES users(user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_university_import_errors_batch' AND conrelid = 'university_import_errors'::regclass) THEN
        ALTER TABLE university_import_errors ADD CONSTRAINT fk_university_import_errors_batch FOREIGN KEY (import_batch_id) REFERENCES university_import_batches(import_batch_id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_audit_logs_university' AND conrelid = 'audit_logs'::regclass) THEN
        ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_university_domains_university
    ON university_domains(university_id, status);

CREATE INDEX IF NOT EXISTS ix_university_admins_university
    ON university_admins(university_id, status);

CREATE INDEX IF NOT EXISTS ix_university_rosters_lookup
    ON university_student_rosters(university_id, status, email);

CREATE INDEX IF NOT EXISTS ix_university_rosters_matched_user
    ON university_student_rosters(matched_user_id);

CREATE INDEX IF NOT EXISTS ix_university_import_batches_university
    ON university_import_batches(university_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_logs_university_time
    ON audit_logs(university_id, performed_at DESC);
