-- UniBus shared database schema snapshot
-- Source of truth: current shared PostgreSQL database after V6__drop_verification_codes_and_eta.sql.
-- Excludes Flyway's own flyway_schema_history table.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS ai_chat_history (
    chat_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    chat_session_id UUID DEFAULT gen_random_uuid() NOT NULL,
    message_role VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    advisory_type VARCHAR(20),
    sent_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_ai_chat_history PRIMARY KEY (chat_history_id),
    CONSTRAINT ai_chat_history_advisory_type_check CHECK (((advisory_type)::text = ANY ((ARRAY['ROUTE_SUGGESTION'::character varying, 'FARE_LOOKUP'::character varying, 'SCHEDULE_LOOKUP'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT ai_chat_history_message_role_check CHECK (((message_role)::text = ANY ((ARRAY['USER'::character varying, 'AI'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    performed_by_user_id INTEGER NOT NULL,
    university_id INTEGER,
    action VARCHAR(50) NOT NULL,
    affected_table VARCHAR(50),
    affected_record_id VARCHAR(50),
    old_values TEXT,
    new_values TEXT,
    ip_address VARCHAR(45),
    result VARCHAR(30),
    request_id VARCHAR(80),
    notes VARCHAR(500),
    performed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id)
);

CREATE TABLE IF NOT EXISTS bus_schedules (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id INTEGER NOT NULL,
    bus_id INTEGER,
    driver_id INTEGER,
    conductor_id INTEGER,
    weekday_number INTEGER NOT NULL,
    departure_time TIME NOT NULL,
    end_time TIME,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    assigned_by_user_id INTEGER,
    assigned_at TIMESTAMPTZ,
    CONSTRAINT pk_bus_schedules PRIMARY KEY (schedule_id),
    CONSTRAINT bus_schedules_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT bus_schedules_weekday_number_check CHECK (((weekday_number >= 1) AND (weekday_number <= 7)))
);

CREATE TABLE IF NOT EXISTS buses (
    bus_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    license_plate VARCHAR(15) NOT NULL,
    seat_count INTEGER NOT NULL,
    bus_type VARCHAR(50),
    manufacture_year INTEGER,
    status VARCHAR(20) DEFAULT 'READY'::character varying NOT NULL,
    CONSTRAINT pk_buses PRIMARY KEY (bus_id),
    CONSTRAINT uq_buses_license_plate UNIQUE (license_plate),
    CONSTRAINT buses_status_check CHECK (((status)::text = ANY ((ARRAY['READY'::character varying, 'RUNNING'::character varying, 'MAINTENANCE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS complaints (
    complaint_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submitted_by_user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'OPEN'::character varying NOT NULL,
    resolution VARCHAR(2000),
    handled_by_user_id INTEGER,
    handled_at TIMESTAMPTZ,
    CONSTRAINT pk_complaints PRIMARY KEY (complaint_id),
    CONSTRAINT complaints_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS conductors (
    conductor_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    employee_code VARCHAR(20) NOT NULL,
    CONSTRAINT pk_conductors PRIMARY KEY (conductor_id),
    CONSTRAINT uq_conductors_employee_code UNIQUE (employee_code),
    CONSTRAINT uq_conductors_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS daily_statistics (
    daily_statistic_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    statistics_date DATE NOT NULL,
    route_id INTEGER,
    completed_trip_count INTEGER DEFAULT 0 NOT NULL,
    cancelled_trip_count INTEGER DEFAULT 0 NOT NULL,
    traveling_student_count INTEGER DEFAULT 0 NOT NULL,
    qr_scan_count INTEGER DEFAULT 0 NOT NULL,
    revenue_amount NUMERIC(15,0) DEFAULT 0 NOT NULL,
    monthly_passes_sold INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_daily_statistics PRIMARY KEY (daily_statistic_id)
);

CREATE TABLE IF NOT EXISTS dispatchers (
    dispatcher_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    employee_code VARCHAR(20) NOT NULL,
    department VARCHAR(100),
    CONSTRAINT pk_dispatchers PRIMARY KEY (dispatcher_id),
    CONSTRAINT uq_dispatchers_employee_code UNIQUE (employee_code),
    CONSTRAINT uq_dispatchers_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS driver_ratings (
    driver_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    driver_id INTEGER NOT NULL,
    trip_id INTEGER,
    stars INTEGER NOT NULL,
    comment VARCHAR(1000),
    rated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_driver_ratings PRIMARY KEY (driver_rating_id),
    CONSTRAINT uq_driver_ratings_student_trip UNIQUE (student_code, trip_id),
    CONSTRAINT driver_ratings_stars_check CHECK (((stars >= 1) AND (stars <= 5)))
);

CREATE TABLE IF NOT EXISTS drivers (
    driver_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    license_number VARCHAR(50) NOT NULL,
    years_experience INTEGER DEFAULT 0,
    average_rating NUMERIC(3,2) DEFAULT 0.00,
    work_status VARCHAR(20) DEFAULT 'READY'::character varying NOT NULL,
    CONSTRAINT pk_drivers PRIMARY KEY (driver_id),
    CONSTRAINT uq_drivers_license UNIQUE (license_number),
    CONSTRAINT uq_drivers_user UNIQUE (user_id),
    CONSTRAINT drivers_work_status_check CHECK (((work_status)::text = ANY ((ARRAY['READY'::character varying, 'RUNNING'::character varying, 'ON_LEAVE'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS fares (
    fare_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id INTEGER NOT NULL,
    fare_type VARCHAR(10) NOT NULL,
    amount NUMERIC(12,0) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    adjusted_by_user_id INTEGER,
    notes VARCHAR(500),
    CONSTRAINT pk_fares PRIMARY KEY (fare_id),
    CONSTRAINT fares_fare_type_check CHECK (((fare_type)::text = ANY ((ARRAY['SINGLE'::character varying, 'MONTHLY'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    trip_id INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    star_rating INTEGER,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'OPEN'::character varying NOT NULL,
    response VARCHAR(1000),
    handled_by_user_id INTEGER,
    CONSTRAINT pk_feedback PRIMARY KEY (feedback_id),
    CONSTRAINT feedback_star_rating_check CHECK (((star_rating >= 1) AND (star_rating <= 5))),
    CONSTRAINT feedback_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS incidents (
    incident_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conductor_id INTEGER NOT NULL,
    trip_id INTEGER NOT NULL,
    incident_type VARCHAR(20) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    reported_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'NEW'::character varying NOT NULL,
    resolution VARCHAR(1000),
    handled_by_user_id INTEGER,
    CONSTRAINT pk_incidents PRIMARY KEY (incident_id),
    CONSTRAINT incidents_incident_type_check CHECK (((incident_type)::text = ANY ((ARRAY['OVERCROWDED'::character varying, 'EMERGENCY'::character varying, 'TECHNICAL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT incidents_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS internal_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_user_id INTEGER NOT NULL,
    recipient_user_id INTEGER NOT NULL,
    trip_id INTEGER,
    content VARCHAR(2000) NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_internal_messages PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_id INTEGER NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    description VARCHAR(500) NOT NULL,
    amount NUMERIC(12,0) NOT NULL,
    original_amount NUMERIC(12,0),
    subsidy_amount NUMERIC(12,0),
    final_amount NUMERIC(12,0),
    issued_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (invoice_id),
    CONSTRAINT uq_invoices_payment UNIQUE (payment_id)
);

CREATE TABLE IF NOT EXISTS login_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    device VARCHAR(200),
    ip_address VARCHAR(45),
    signed_in_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    signed_out_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true NOT NULL,
    CONSTRAINT pk_login_sessions PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS lost_item_reports (
    lost_item_report_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_user_id INTEGER NOT NULL,
    trip_id INTEGER,
    item_description VARCHAR(500) NOT NULL,
    reported_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'REPORTED'::character varying NOT NULL,
    notes VARCHAR(500),
    assisted_by_user_id INTEGER,
    CONSTRAINT pk_lost_item_reports PRIMARY KEY (lost_item_report_id),
    CONSTRAINT lost_item_reports_status_check CHECK (((status)::text = ANY ((ARRAY['REPORTED'::character varying, 'SEARCHING'::character varying, 'FOUND'::character varying, 'NOT_FOUND'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS monthly_passes (
    monthly_pass_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    route_id INTEGER NOT NULL,
    effective_month INTEGER NOT NULL,
    effective_year INTEGER NOT NULL,
    valid_from DATE NOT NULL,
    purchased_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_on DATE NOT NULL,
    fare_amount NUMERIC(12,0) NOT NULL,
    original_fare_amount NUMERIC(12,0),
    subsidy_amount NUMERIC(12,0),
    final_fare_amount NUMERIC(12,0),
    subsidy_policy_id INTEGER,
    qr_code VARCHAR(255),
    last_scanned_at TIMESTAMPTZ,
    scans_today INTEGER DEFAULT 0 NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    CONSTRAINT pk_monthly_passes PRIMARY KEY (monthly_pass_id),
    CONSTRAINT monthly_passes_effective_month_check CHECK (((effective_month >= 1) AND (effective_month <= 12))),
    CONSTRAINT monthly_passes_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_user_id INTEGER,
    sender_user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    notification_type VARCHAR(20) DEFAULT 'SYSTEM'::character varying NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT notifications_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'TRIP'::character varying, 'PAYMENT'::character varying, 'COMPLAINT'::character varying, 'ALERT'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    amount NUMERIC(12,0) NOT NULL,
    method VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING'::character varying NOT NULL,
    transaction_code VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    monthly_pass_id INTEGER,
    single_trip_ticket_id INTEGER,
    notes VARCHAR(500),
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT ck_payments_one_ticket_type CHECK ((NOT ((monthly_pass_id IS NOT NULL) AND (single_trip_ticket_id IS NOT NULL)))),
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK_TRANSFER'::character varying, 'E_WALLET'::character varying, 'CARD'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS route_registrations (
    registration_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    route_id INTEGER NOT NULL,
    boarding_stop_id INTEGER,
    alighting_stop_id INTEGER,
    registered_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    effective_date DATE,
    status VARCHAR(20) DEFAULT 'PENDING'::character varying NOT NULL,
    previous_registration_id INTEGER,
    cancellation_reason VARCHAR(500),
    approved_by_user_id INTEGER,
    approved_at TIMESTAMPTZ,
    CONSTRAINT pk_route_registrations PRIMARY KEY (registration_id),
    CONSTRAINT route_registrations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS route_stops (
    route_stop_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id INTEGER NOT NULL,
    stop_id INTEGER NOT NULL,
    stop_order INTEGER NOT NULL,
    minutes_from_previous_stop INTEGER,
    CONSTRAINT pk_route_stops PRIMARY KEY (route_stop_id),
    CONSTRAINT uq_route_stops_order UNIQUE (route_id, stop_order)
);

CREATE TABLE IF NOT EXISTS routes (
    route_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    distance_km NUMERIC(10,2),
    estimated_minutes INTEGER,
    is_circular BOOLEAN DEFAULT false NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (route_id),
    CONSTRAINT routes_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS single_trip_tickets (
    single_trip_ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    route_id INTEGER NOT NULL,
    boarding_stop_id INTEGER,
    alighting_stop_id INTEGER,
    used_on_trip_id INTEGER,
    fare_amount NUMERIC(12,0) NOT NULL,
    qr_code VARCHAR(255),
    purchased_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_scanned_at TIMESTAMPTZ,
    scanned_by_conductor_id INTEGER,
    status VARCHAR(20) DEFAULT 'UNUSED'::character varying NOT NULL,
    CONSTRAINT pk_single_trip_tickets PRIMARY KEY (single_trip_ticket_id),
    CONSTRAINT single_trip_tickets_status_check CHECK (((status)::text = ANY ((ARRAY['UNUSED'::character varying, 'USED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS stops (
    stop_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    longitude NUMERIC(11,8),
    latitude NUMERIC(10,8),
    description VARCHAR(500),
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_user_id INTEGER,
    CONSTRAINT pk_stops PRIMARY KEY (stop_id),
    CONSTRAINT stops_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS student_verifications (
    student_verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    university_id INTEGER,
    university VARCHAR(150) NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    card_image_url VARCHAR(500),
    ocr_full_name VARCHAR(100),
    ocr_student_code VARCHAR(20),
    ocr_university VARCHAR(150),
    ocr_raw_text TEXT,
    ocr_confidence_score NUMERIC(5,4),
    status VARCHAR(30) DEFAULT 'PENDING_REVIEW'::character varying NOT NULL,
    rejection_reason VARCHAR(500),
    reviewer_user_id INTEGER,
    reviewed_at TIMESTAMPTZ,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    is_current BOOLEAN DEFAULT true NOT NULL,
    CONSTRAINT pk_student_verifications PRIMARY KEY (student_verification_id),
    CONSTRAINT ck_student_verifications_ocr_confidence CHECK (((ocr_confidence_score IS NULL) OR ((ocr_confidence_score >= (0)::numeric) AND (ocr_confidence_score <= (1)::numeric)))),
    CONSTRAINT ck_student_verifications_status CHECK (((status)::text = ANY ((ARRAY['NOT_SUBMITTED'::character varying, 'PENDING_REVIEW'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'RESUBMISSION_REQUIRED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS students (
    student_code VARCHAR(20) NOT NULL,
    user_id INTEGER NOT NULL,
    university VARCHAR(150) NOT NULL,
    university_id INTEGER,
    faculty VARCHAR(100),
    academic_year INTEGER,
    date_of_birth DATE,
    CONSTRAINT pk_students PRIMARY KEY (student_code),
    CONSTRAINT uq_students_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS support_tickets (
    support_ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submitted_by_user_id INTEGER NOT NULL,
    support_type VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    status VARCHAR(20) DEFAULT 'NEW'::character varying NOT NULL,
    response VARCHAR(2000),
    handled_by_user_id INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_support_tickets PRIMARY KEY (support_ticket_id),
    CONSTRAINT support_tickets_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT support_tickets_support_type_check CHECK (((support_type)::text = ANY ((ARRAY['ACCOUNT'::character varying, 'PAYMENT'::character varying, 'TECHNICAL'::character varying, 'MONTHLY_PASS'::character varying, 'OTHER'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS travel_history (
    travel_history_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    trip_id INTEGER NOT NULL,
    registration_id INTEGER,
    boarding_stop_id INTEGER,
    alighting_stop_id INTEGER,
    boarded_at TIMESTAMPTZ,
    alighted_at TIMESTAMPTZ,
    confirmation_method VARCHAR(20),
    confirmed_by_conductor_id INTEGER,
    CONSTRAINT pk_travel_history PRIMARY KEY (travel_history_id),
    CONSTRAINT travel_history_confirmation_method_check CHECK (((confirmation_method)::text = ANY ((ARRAY['QR_SCAN'::character varying, 'MANUAL'::character varying, 'SYSTEM'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS trips (
    trip_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_id INTEGER,
    route_id INTEGER NOT NULL,
    bus_id INTEGER NOT NULL,
    driver_id INTEGER NOT NULL,
    conductor_id INTEGER,
    service_date DATE NOT NULL,
    departed_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    status VARCHAR(20) DEFAULT 'NOT_STARTED'::character varying NOT NULL,
    notes VARCHAR(500),
    CONSTRAINT pk_trips PRIMARY KEY (trip_id),
    CONSTRAINT trips_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS user_auth_providers (
    user_auth_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(191) NOT NULL,
    provider_email VARCHAR(100) NOT NULL,
    provider_email_verified BOOLEAN DEFAULT false NOT NULL,
    display_name VARCHAR(100),
    avatar_url VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_user_auth_providers PRIMARY KEY (user_auth_provider_id),
    CONSTRAINT uq_user_auth_providers_provider_uid UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_user_auth_providers_user_provider UNIQUE (user_id, provider),
    CONSTRAINT ck_user_auth_providers_provider CHECK (((provider)::text = 'GOOGLE'::text))
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255),
    full_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(15),
    address VARCHAR(255),
    avatar_url VARCHAR(500),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(10) DEFAULT 'ACTIVE'::character varying NOT NULL,
    lock_reason VARCHAR(500),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    email_verified_at TIMESTAMPTZ,
    student_verification_status VARCHAR(30) DEFAULT 'NOT_SUBMITTED'::character varying NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_student_verification_status CHECK (((student_verification_status)::text = ANY ((ARRAY['NOT_SUBMITTED'::character varying, 'PENDING_REVIEW'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying, 'RESUBMISSION_REQUIRED'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'DRIVER'::character varying, 'CONDUCTOR'::character varying, 'DISPATCHER'::character varying, 'UNIVERSITY_ADMIN'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS universities (
    university_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    short_name VARCHAR(80),
    contact_email VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_universities PRIMARY KEY (university_id),
    CONSTRAINT uq_universities_code UNIQUE (code),
    CONSTRAINT uq_universities_name UNIQUE (name),
    CONSTRAINT ck_universities_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS campuses (
    campus_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    latitude NUMERIC(10,8),
    longitude NUMERIC(11,8),
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_campuses PRIMARY KEY (campus_id),
    CONSTRAINT uq_campuses_university_code UNIQUE (university_id, code),
    CONSTRAINT ck_campuses_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS route_universities (
    route_university_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id INTEGER NOT NULL,
    university_id INTEGER NOT NULL,
    campus_id INTEGER,
    active_from DATE DEFAULT CURRENT_DATE NOT NULL,
    active_until DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_route_universities PRIMARY KEY (route_university_id),
    CONSTRAINT ck_route_universities_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT ck_route_universities_dates CHECK ((active_until IS NULL OR active_until >= active_from))
);

CREATE TABLE IF NOT EXISTS subsidy_policies (
    subsidy_policy_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    campus_id INTEGER,
    policy_name VARCHAR(150) NOT NULL,
    subsidy_type VARCHAR(20) NOT NULL,
    "value" NUMERIC(12,2) NOT NULL,
    max_amount NUMERIC(12,0),
    active_from DATE DEFAULT CURRENT_DATE NOT NULL,
    active_until DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_subsidy_policies PRIMARY KEY (subsidy_policy_id),
    CONSTRAINT ck_subsidy_policies_type CHECK (((subsidy_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED_AMOUNT'::character varying])::text[]))),
    CONSTRAINT ck_subsidy_policies_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT ck_subsidy_policies_value CHECK (("value" >= 0)),
    CONSTRAINT ck_subsidy_policies_max CHECK ((max_amount IS NULL OR max_amount >= 0)),
    CONSTRAINT ck_subsidy_policies_dates CHECK ((active_until IS NULL OR active_until >= active_from))
);

CREATE TABLE IF NOT EXISTS university_domains (
    university_domain_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    domain VARCHAR(120) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_domains PRIMARY KEY (university_domain_id),
    CONSTRAINT uq_university_domains_domain UNIQUE (domain),
    CONSTRAINT ck_university_domains_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS university_admins (
    university_admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    title VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by_user_id INTEGER,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_admins PRIMARY KEY (university_admin_id),
    CONSTRAINT uq_university_admins_user UNIQUE (user_id),
    CONSTRAINT ck_university_admins_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS university_student_rosters (
    roster_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    email VARCHAR(100) NOT NULL,
    student_code VARCHAR(20) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    faculty VARCHAR(100),
    academic_year INTEGER,
    status VARCHAR(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    matched_user_id INTEGER,
    imported_batch_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_university_student_rosters PRIMARY KEY (roster_id),
    CONSTRAINT uq_university_roster_email UNIQUE (university_id, email),
    CONSTRAINT uq_university_roster_student_code UNIQUE (university_id, student_code),
    CONSTRAINT ck_university_rosters_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'GRADUATED'::character varying, 'SUSPENDED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS university_import_batches (
    import_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id INTEGER NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    total_rows INTEGER DEFAULT 0 NOT NULL,
    success_rows INTEGER DEFAULT 0 NOT NULL,
    error_rows INTEGER DEFAULT 0 NOT NULL,
    status VARCHAR(30) DEFAULT 'PROCESSING'::character varying NOT NULL,
    imported_by_user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT pk_university_import_batches PRIMARY KEY (import_batch_id),
    CONSTRAINT ck_university_import_batches_status CHECK (((status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying, 'COMPLETED_WITH_ERRORS'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS university_import_errors (
    import_error_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    import_batch_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    field_name VARCHAR(80),
    raw_value TEXT,
    error_message VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_university_import_errors PRIMARY KEY (import_error_id)
);

CREATE TABLE IF NOT EXISTS vehicle_locations (
    vehicle_location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_id INTEGER NOT NULL,
    trip_id INTEGER,
    longitude NUMERIC(11,8) NOT NULL,
    latitude NUMERIC(10,8) NOT NULL,
    speed_kmh NUMERIC(5,2),
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_vehicle_locations PRIMARY KEY (vehicle_location_id)
);

CREATE TABLE IF NOT EXISTS violation_reports (
    violation_report_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reported_by_user_id INTEGER NOT NULL,
    reported_user_id INTEGER NOT NULL,
    content VARCHAR(2000) NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'OPEN'::character varying NOT NULL,
    resolution VARCHAR(2000),
    CONSTRAINT pk_violation_reports PRIMARY KEY (violation_report_id),
    CONSTRAINT violation_reports_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying])::text[])))
);

-- Foreign keys are applied after table creation to avoid ordering issues.
ALTER TABLE ai_chat_history ADD CONSTRAINT fk_ai_chat_history_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_performer FOREIGN KEY (performed_by_user_id) REFERENCES users(user_id);
ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE bus_schedules ADD CONSTRAINT fk_bus_schedules_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(user_id);
ALTER TABLE bus_schedules ADD CONSTRAINT fk_bus_schedules_bus FOREIGN KEY (bus_id) REFERENCES buses(bus_id);
ALTER TABLE bus_schedules ADD CONSTRAINT fk_bus_schedules_conductor FOREIGN KEY (conductor_id) REFERENCES conductors(conductor_id);
ALTER TABLE bus_schedules ADD CONSTRAINT fk_bus_schedules_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id);
ALTER TABLE bus_schedules ADD CONSTRAINT fk_bus_schedules_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE complaints ADD CONSTRAINT fk_complaints_handled_by FOREIGN KEY (handled_by_user_id) REFERENCES users(user_id);
ALTER TABLE complaints ADD CONSTRAINT fk_complaints_submitted_by FOREIGN KEY (submitted_by_user_id) REFERENCES users(user_id);
ALTER TABLE conductors ADD CONSTRAINT fk_conductors_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE campuses ADD CONSTRAINT fk_campuses_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE daily_statistics ADD CONSTRAINT fk_daily_statistics_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE dispatchers ADD CONSTRAINT fk_dispatchers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE driver_ratings ADD CONSTRAINT fk_driver_ratings_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id);
ALTER TABLE driver_ratings ADD CONSTRAINT fk_driver_ratings_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE driver_ratings ADD CONSTRAINT fk_driver_ratings_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE drivers ADD CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE fares ADD CONSTRAINT fk_fares_adjusted_by FOREIGN KEY (adjusted_by_user_id) REFERENCES users(user_id);
ALTER TABLE fares ADD CONSTRAINT fk_fares_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE feedback ADD CONSTRAINT fk_feedback_handled_by FOREIGN KEY (handled_by_user_id) REFERENCES users(user_id);
ALTER TABLE feedback ADD CONSTRAINT fk_feedback_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE feedback ADD CONSTRAINT fk_feedback_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE incidents ADD CONSTRAINT fk_incidents_conductor FOREIGN KEY (conductor_id) REFERENCES conductors(conductor_id);
ALTER TABLE incidents ADD CONSTRAINT fk_incidents_handler FOREIGN KEY (handled_by_user_id) REFERENCES users(user_id);
ALTER TABLE incidents ADD CONSTRAINT fk_incidents_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE internal_messages ADD CONSTRAINT fk_messages_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(user_id);
ALTER TABLE internal_messages ADD CONSTRAINT fk_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users(user_id);
ALTER TABLE internal_messages ADD CONSTRAINT fk_messages_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_payment FOREIGN KEY (payment_id) REFERENCES payments(payment_id);
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE login_sessions ADD CONSTRAINT fk_login_sessions_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE lost_item_reports ADD CONSTRAINT fk_lost_items_assistant FOREIGN KEY (assisted_by_user_id) REFERENCES users(user_id);
ALTER TABLE lost_item_reports ADD CONSTRAINT fk_lost_items_reporter FOREIGN KEY (reported_by_user_id) REFERENCES users(user_id);
ALTER TABLE lost_item_reports ADD CONSTRAINT fk_lost_items_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE monthly_passes ADD CONSTRAINT fk_monthly_passes_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE monthly_passes ADD CONSTRAINT fk_monthly_passes_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE monthly_passes ADD CONSTRAINT fk_monthly_passes_subsidy_policy FOREIGN KEY (subsidy_policy_id) REFERENCES subsidy_policies(subsidy_policy_id);
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(user_id);
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_sender FOREIGN KEY (sender_user_id) REFERENCES users(user_id);
ALTER TABLE payments ADD CONSTRAINT fk_payments_monthly_pass FOREIGN KEY (monthly_pass_id) REFERENCES monthly_passes(monthly_pass_id);
ALTER TABLE payments ADD CONSTRAINT fk_payments_single_ticket FOREIGN KEY (single_trip_ticket_id) REFERENCES single_trip_tickets(single_trip_ticket_id);
ALTER TABLE payments ADD CONSTRAINT fk_payments_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_alighting_stop FOREIGN KEY (alighting_stop_id) REFERENCES stops(stop_id);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(user_id);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_boarding_stop FOREIGN KEY (boarding_stop_id) REFERENCES stops(stop_id);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_previous FOREIGN KEY (previous_registration_id) REFERENCES route_registrations(registration_id);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE route_registrations ADD CONSTRAINT fk_registrations_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE route_stops ADD CONSTRAINT fk_route_stops_route FOREIGN KEY (route_id) REFERENCES routes(route_id) ON DELETE CASCADE;
ALTER TABLE route_stops ADD CONSTRAINT fk_route_stops_stop FOREIGN KEY (stop_id) REFERENCES stops(stop_id) ON DELETE CASCADE;
ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_campus FOREIGN KEY (campus_id) REFERENCES campuses(campus_id);
ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE route_universities ADD CONSTRAINT fk_route_universities_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_alighting_stop FOREIGN KEY (alighting_stop_id) REFERENCES stops(stop_id);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_boarding_stop FOREIGN KEY (boarding_stop_id) REFERENCES stops(stop_id);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_scanned_by FOREIGN KEY (scanned_by_conductor_id) REFERENCES conductors(conductor_id);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE single_trip_tickets ADD CONSTRAINT fk_single_tickets_used_trip FOREIGN KEY (used_on_trip_id) REFERENCES trips(trip_id);
ALTER TABLE stops ADD CONSTRAINT fk_stops_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(user_id);
ALTER TABLE student_verifications ADD CONSTRAINT fk_student_verifications_reviewer FOREIGN KEY (reviewer_user_id) REFERENCES users(user_id);
ALTER TABLE student_verifications ADD CONSTRAINT fk_student_verifications_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE student_verifications ADD CONSTRAINT fk_student_verifications_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE students ADD CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE students ADD CONSTRAINT fk_students_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE subsidy_policies ADD CONSTRAINT fk_subsidy_policies_campus FOREIGN KEY (campus_id) REFERENCES campuses(campus_id);
ALTER TABLE subsidy_policies ADD CONSTRAINT fk_subsidy_policies_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE support_tickets ADD CONSTRAINT fk_support_tickets_handler FOREIGN KEY (handled_by_user_id) REFERENCES users(user_id);
ALTER TABLE support_tickets ADD CONSTRAINT fk_support_tickets_submitter FOREIGN KEY (submitted_by_user_id) REFERENCES users(user_id);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_alighting_stop FOREIGN KEY (alighting_stop_id) REFERENCES stops(stop_id);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_boarding_stop FOREIGN KEY (boarding_stop_id) REFERENCES stops(stop_id);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_conductor FOREIGN KEY (confirmed_by_conductor_id) REFERENCES conductors(conductor_id);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_registration FOREIGN KEY (registration_id) REFERENCES route_registrations(registration_id);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_student FOREIGN KEY (student_code) REFERENCES students(student_code);
ALTER TABLE travel_history ADD CONSTRAINT fk_travel_history_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE trips ADD CONSTRAINT fk_trips_bus FOREIGN KEY (bus_id) REFERENCES buses(bus_id);
ALTER TABLE trips ADD CONSTRAINT fk_trips_conductor FOREIGN KEY (conductor_id) REFERENCES conductors(conductor_id);
ALTER TABLE trips ADD CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id);
ALTER TABLE trips ADD CONSTRAINT fk_trips_route FOREIGN KEY (route_id) REFERENCES routes(route_id);
ALTER TABLE trips ADD CONSTRAINT fk_trips_schedule FOREIGN KEY (schedule_id) REFERENCES bus_schedules(schedule_id);
ALTER TABLE user_auth_providers ADD CONSTRAINT fk_user_auth_providers_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(user_id);
ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE university_admins ADD CONSTRAINT fk_university_admins_user FOREIGN KEY (user_id) REFERENCES users(user_id);
ALTER TABLE university_domains ADD CONSTRAINT fk_university_domains_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE university_import_batches ADD CONSTRAINT fk_university_import_batches_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE university_import_batches ADD CONSTRAINT fk_university_import_batches_user FOREIGN KEY (imported_by_user_id) REFERENCES users(user_id);
ALTER TABLE university_import_errors ADD CONSTRAINT fk_university_import_errors_batch FOREIGN KEY (import_batch_id) REFERENCES university_import_batches(import_batch_id) ON DELETE CASCADE;
ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_batch FOREIGN KEY (imported_batch_id) REFERENCES university_import_batches(import_batch_id);
ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_university FOREIGN KEY (university_id) REFERENCES universities(university_id);
ALTER TABLE university_student_rosters ADD CONSTRAINT fk_university_rosters_user FOREIGN KEY (matched_user_id) REFERENCES users(user_id);
ALTER TABLE vehicle_locations ADD CONSTRAINT fk_vehicle_locations_bus FOREIGN KEY (bus_id) REFERENCES buses(bus_id);
ALTER TABLE vehicle_locations ADD CONSTRAINT fk_vehicle_locations_trip FOREIGN KEY (trip_id) REFERENCES trips(trip_id);
ALTER TABLE violation_reports ADD CONSTRAINT fk_violation_reports_reporter FOREIGN KEY (reported_by_user_id) REFERENCES users(user_id);
ALTER TABLE violation_reports ADD CONSTRAINT fk_violation_reports_subject FOREIGN KEY (reported_user_id) REFERENCES users(user_id);

CREATE INDEX IF NOT EXISTS ix_ai_chat_user_time ON public.ai_chat_history USING btree (user_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action_time ON public.audit_logs USING btree (action, performed_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_performer_time ON public.audit_logs USING btree (performed_by_user_id, performed_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_university_time ON public.audit_logs USING btree (university_id, performed_at DESC);
CREATE INDEX IF NOT EXISTS ix_complaints_status ON public.complaints USING btree (status);
CREATE INDEX IF NOT EXISTS ix_daily_statistics_date_route ON public.daily_statistics USING btree (statistics_date DESC, route_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_statistics_route_date ON public.daily_statistics USING btree (statistics_date, route_id) WHERE (route_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uq_daily_statistics_system_date ON public.daily_statistics USING btree (statistics_date) WHERE (route_id IS NULL);
CREATE INDEX IF NOT EXISTS ix_driver_ratings_driver ON public.driver_ratings USING btree (driver_id);
CREATE INDEX IF NOT EXISTS ix_feedback_status ON public.feedback USING btree (status);
CREATE INDEX IF NOT EXISTS ix_messages_recipient_read ON public.internal_messages USING btree (recipient_user_id, is_read) INCLUDE (sent_at, sender_user_id);
CREATE INDEX IF NOT EXISTS ix_login_sessions_user_active ON public.login_sessions USING btree (user_id, is_active) INCLUDE (expires_at, token_hash);
CREATE INDEX IF NOT EXISTS ix_monthly_passes_status_expiration ON public.monthly_passes USING btree (status, expires_on) INCLUDE (student_code, route_id, qr_code, last_scanned_at);
CREATE INDEX IF NOT EXISTS ix_monthly_passes_student_period ON public.monthly_passes USING btree (student_code, effective_month, effective_year);
CREATE INDEX IF NOT EXISTS ix_notifications_recipient_read ON public.notifications USING btree (recipient_user_id, is_read);
CREATE INDEX IF NOT EXISTS ix_payments_status ON public.payments USING btree (status);
CREATE INDEX IF NOT EXISTS ix_payments_student ON public.payments USING btree (student_code);
CREATE INDEX IF NOT EXISTS ix_single_tickets_status_expiration ON public.single_trip_tickets USING btree (status, expires_at) INCLUDE (student_code, route_id, qr_code);
CREATE INDEX IF NOT EXISTS ix_single_tickets_student_purchase ON public.single_trip_tickets USING btree (student_code, purchased_at DESC);
CREATE INDEX IF NOT EXISTS ix_student_verifications_status ON public.student_verifications USING btree (status, submitted_at DESC);
CREATE INDEX IF NOT EXISTS ix_student_verifications_university ON public.student_verifications USING btree (university_id);
CREATE INDEX IF NOT EXISTS ix_students_university ON public.students USING btree (university_id);
CREATE INDEX IF NOT EXISTS ix_route_universities_lookup ON public.route_universities USING btree (university_id, route_id, status, active_from, active_until);
CREATE INDEX IF NOT EXISTS ix_subsidy_policies_lookup ON public.subsidy_policies USING btree (university_id, status, active_from, active_until);
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_student_code ON public.student_verifications USING btree (student_code) WHERE (is_current AND ((status)::text = ANY ((ARRAY['PENDING_REVIEW'::character varying, 'VERIFIED'::character varying, 'RESUBMISSION_REQUIRED'::character varying])::text[])));
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_user ON public.student_verifications USING btree (user_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_travel_history_student ON public.travel_history USING btree (student_code);
CREATE INDEX IF NOT EXISTS ix_trips_driver_date ON public.trips USING btree (driver_id, service_date);
CREATE INDEX IF NOT EXISTS ix_trips_route_status ON public.trips USING btree (route_id, status) INCLUDE (bus_id, service_date);
CREATE INDEX IF NOT EXISTS ix_trips_service_date ON public.trips USING btree (service_date);
CREATE INDEX IF NOT EXISTS ix_trips_status ON public.trips USING btree (status);
CREATE INDEX IF NOT EXISTS ix_user_auth_providers_user ON public.user_auth_providers USING btree (user_id);
CREATE INDEX IF NOT EXISTS ix_users_role ON public.users USING btree (role);
CREATE INDEX IF NOT EXISTS ix_users_status ON public.users USING btree (status);
CREATE INDEX IF NOT EXISTS ix_university_admins_university ON public.university_admins USING btree (university_id, status);
CREATE INDEX IF NOT EXISTS ix_university_domains_university ON public.university_domains USING btree (university_id, status);
CREATE INDEX IF NOT EXISTS ix_university_import_batches_university ON public.university_import_batches USING btree (university_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_university_rosters_lookup ON public.university_student_rosters USING btree (university_id, status, email);
CREATE INDEX IF NOT EXISTS ix_university_rosters_matched_user ON public.university_student_rosters USING btree (matched_user_id);
CREATE INDEX IF NOT EXISTS ix_vehicle_locations_bus_time ON public.vehicle_locations USING btree (bus_id, updated_at DESC);
