-- =====================================================================
-- DATABASE SCHEMA OPTION: Student Bus Management System
-- Reduced PostgreSQL design, 25 application tables
-- =====================================================================
-- This is a review/reference schema derived from DBConverted.sql.
-- It is not a drop-in migration for the current backend without mapping
-- entity names and repositories.
--
-- Main reductions:
--   * drivers, conductors, dispatchers -> staff_profiles
--   * monthly_passes, single_trip_tickets -> tickets
--   * complaints, support_tickets, violation_reports, lost_item_reports,
--     incidents, and general feedback -> cases
--   * notifications, internal_messages -> communications
--   * invoices are represented by payment invoice fields
--   * daily_statistics is intentionally omitted; use a view/materialized view
--   * email/password and OAuth are split through user_auth_providers
--   * student verification evidence is tracked before creating/updating students
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

BEGIN;

-- =====================================================================
-- SECTION 1: USERS AND ACTORS
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    user_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email               VARCHAR(100) NOT NULL,
    password_hash       VARCHAR(255),
    full_name           VARCHAR(100) NOT NULL,
    phone_number        VARCHAR(15),
    address             VARCHAR(255),
    avatar_url          VARCHAR(500),
    role                VARCHAR(20) NOT NULL
                        CHECK (role IN ('STUDENT', 'DRIVER', 'CONDUCTOR', 'DISPATCHER', 'ADMIN')),
    status              VARCHAR(10) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'LOCKED')),
    lock_reason         VARCHAR(500),
    email_verified_at   TIMESTAMPTZ,
    student_verification_status VARCHAR(30) NOT NULL DEFAULT 'NOT_SUBMITTED'
                        CHECK (student_verification_status IN (
                            'NOT_SUBMITTED',
                            'PENDING_REVIEW',
                            'VERIFIED',
                            'REJECTED',
                            'RESUBMISSION_REQUIRED'
                        )),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS students (
    student_code        VARCHAR(20) NOT NULL,
    user_id             INTEGER NOT NULL,
    university          VARCHAR(150) NOT NULL,
    faculty             VARCHAR(100),
    academic_year       INTEGER CHECK (academic_year IS NULL OR academic_year > 0),
    date_of_birth       DATE,

    CONSTRAINT pk_students PRIMARY KEY (student_code),
    CONSTRAINT uq_students_user UNIQUE (user_id),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS staff_profiles (
    staff_id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             INTEGER NOT NULL,
    employee_code       VARCHAR(20),
    department          VARCHAR(100),
    license_number      VARCHAR(50),
    years_experience    INTEGER NOT NULL DEFAULT 0 CHECK (years_experience >= 0),
    work_status         VARCHAR(20) NOT NULL DEFAULT 'READY'
                        CHECK (work_status IN ('READY', 'RUNNING', 'ON_LEAVE')),

    CONSTRAINT pk_staff_profiles PRIMARY KEY (staff_id),
    CONSTRAINT uq_staff_profiles_user UNIQUE (user_id),
    CONSTRAINT uq_staff_profiles_employee_code UNIQUE (employee_code),
    CONSTRAINT uq_staff_profiles_license UNIQUE (license_number),
    CONSTRAINT fk_staff_profiles_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS login_sessions (
    session_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             INTEGER NOT NULL,
    token_hash          VARCHAR(255) NOT NULL,
    device              VARCHAR(200),
    ip_address          VARCHAR(45),
    signed_in_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMPTZ NOT NULL,
    signed_out_at       TIMESTAMPTZ,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_login_sessions PRIMARY KEY (session_id),
    CONSTRAINT fk_login_sessions_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_login_sessions_time CHECK (expires_at > signed_in_at)
);

CREATE TABLE IF NOT EXISTS verification_codes (
    verification_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                VARCHAR(100) NOT NULL,
    purpose              VARCHAR(20) NOT NULL
                         CHECK (purpose IN ('REGISTER', 'RESET_PASSWORD')),
    code_hash            VARCHAR(255) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at           TIMESTAMPTZ NOT NULL,
    consumed_at          TIMESTAMPTZ,
    attempt_count        INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),

    CONSTRAINT pk_verification_codes PRIMARY KEY (verification_code_id),
    CONSTRAINT ck_verification_codes_time CHECK (expires_at > created_at)
);

CREATE TABLE IF NOT EXISTS user_auth_providers (
    user_auth_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               INTEGER NOT NULL,
    provider              VARCHAR(30) NOT NULL
                         CHECK (provider IN ('GOOGLE')),
    provider_user_id      VARCHAR(191) NOT NULL,
    provider_email        VARCHAR(100) NOT NULL,
    provider_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    display_name          VARCHAR(100),
    avatar_url            VARCHAR(500),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ,

    CONSTRAINT pk_user_auth_providers PRIMARY KEY (user_auth_provider_id),
    CONSTRAINT uq_user_auth_providers_provider_uid UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_user_auth_providers_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_user_auth_providers_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS student_verifications (
    student_verification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 INTEGER NOT NULL,
    university              VARCHAR(150) NOT NULL,
    student_code            VARCHAR(20) NOT NULL,
    card_image_url          VARCHAR(500),
    ocr_full_name           VARCHAR(100),
    ocr_student_code        VARCHAR(20),
    ocr_university          VARCHAR(150),
    ocr_raw_text            TEXT,
    ocr_confidence_score    NUMERIC(5,4)
                            CHECK (
                                ocr_confidence_score IS NULL
                                OR ocr_confidence_score BETWEEN 0 AND 1
                            ),
    status                  VARCHAR(30) NOT NULL DEFAULT 'PENDING_REVIEW'
                            CHECK (status IN (
                                'NOT_SUBMITTED',
                                'PENDING_REVIEW',
                                'VERIFIED',
                                'REJECTED',
                                'RESUBMISSION_REQUIRED'
                            )),
    rejection_reason        VARCHAR(500),
    reviewer_user_id        INTEGER,
    reviewed_at             TIMESTAMPTZ,
    submitted_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ,
    is_current              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_student_verifications PRIMARY KEY (student_verification_id),
    CONSTRAINT fk_student_verifications_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_student_verifications_reviewer FOREIGN KEY (reviewer_user_id)
        REFERENCES users(user_id)
);

-- =====================================================================
-- SECTION 2: ROUTES, STOPS AND BUSES
-- =====================================================================

CREATE TABLE IF NOT EXISTS routes (
    route_id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_name          VARCHAR(150) NOT NULL,
    description         VARCHAR(500),
    distance_km         NUMERIC(10,2) CHECK (distance_km IS NULL OR distance_km >= 0),
    estimated_minutes   INTEGER CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    is_circular         BOOLEAN NOT NULL DEFAULT FALSE,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_routes PRIMARY KEY (route_id)
);

CREATE TABLE IF NOT EXISTS stops (
    stop_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_name           VARCHAR(150) NOT NULL,
    address             VARCHAR(255),
    longitude           NUMERIC(11,8) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    latitude            NUMERIC(10,8) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    description         VARCHAR(500),
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id  INTEGER,

    CONSTRAINT pk_stops PRIMARY KEY (stop_id),
    CONSTRAINT fk_stops_created_by FOREIGN KEY (created_by_user_id)
        REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS route_stops (
    route_stop_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id            INTEGER NOT NULL,
    stop_id             INTEGER NOT NULL,
    stop_order          INTEGER NOT NULL CHECK (stop_order > 0),
    minutes_from_previous_stop INTEGER CHECK (
        minutes_from_previous_stop IS NULL OR minutes_from_previous_stop >= 0
    ),

    CONSTRAINT pk_route_stops PRIMARY KEY (route_stop_id),
    CONSTRAINT uq_route_stops_order UNIQUE (route_id, stop_order),
    CONSTRAINT uq_route_stops_route_member UNIQUE (route_id, route_stop_id),
    CONSTRAINT fk_route_stops_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id) ON DELETE CASCADE,
    CONSTRAINT fk_route_stops_stop FOREIGN KEY (stop_id)
        REFERENCES stops(stop_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS buses (
    bus_id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    license_plate       VARCHAR(15) NOT NULL,
    seat_count          INTEGER NOT NULL CHECK (seat_count > 0),
    bus_type            VARCHAR(50),
    manufacture_year    INTEGER CHECK (manufacture_year IS NULL OR manufacture_year >= 1980),
    status              VARCHAR(20) NOT NULL DEFAULT 'READY'
                        CHECK (status IN ('READY', 'RUNNING', 'MAINTENANCE')),

    CONSTRAINT pk_buses PRIMARY KEY (bus_id),
    CONSTRAINT uq_buses_license_plate UNIQUE (license_plate)
);

-- =====================================================================
-- SECTION 3: SCHEDULES, TRIPS AND ETAS
-- =====================================================================

CREATE TABLE IF NOT EXISTS bus_schedules (
    schedule_id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id            INTEGER NOT NULL,
    bus_id              INTEGER NOT NULL,
    driver_staff_id     INTEGER NOT NULL,
    conductor_staff_id  INTEGER,
    weekday_number      INTEGER NOT NULL CHECK (weekday_number BETWEEN 1 AND 7),
    departure_time      TIME NOT NULL,
    end_time            TIME,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CANCELLED')),
    assigned_by_user_id INTEGER,
    assigned_at         TIMESTAMPTZ,

    CONSTRAINT pk_bus_schedules PRIMARY KEY (schedule_id),
    CONSTRAINT uq_bus_schedules_route_departure UNIQUE (route_id, weekday_number, departure_time),
    CONSTRAINT uq_bus_schedules_bus_departure UNIQUE (bus_id, weekday_number, departure_time),
    CONSTRAINT uq_bus_schedules_driver_departure UNIQUE (driver_staff_id, weekday_number, departure_time),
    CONSTRAINT fk_bus_schedules_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id),
    CONSTRAINT fk_bus_schedules_bus FOREIGN KEY (bus_id)
        REFERENCES buses(bus_id),
    CONSTRAINT fk_bus_schedules_driver FOREIGN KEY (driver_staff_id)
        REFERENCES staff_profiles(staff_id),
    CONSTRAINT fk_bus_schedules_conductor FOREIGN KEY (conductor_staff_id)
        REFERENCES staff_profiles(staff_id),
    CONSTRAINT fk_bus_schedules_assigned_by FOREIGN KEY (assigned_by_user_id)
        REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS trips (
    trip_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_id         INTEGER NOT NULL,
    service_date        DATE NOT NULL,
    departed_at         TIMESTAMPTZ,
    ended_at            TIMESTAMPTZ,
    status              VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED'
                        CHECK (status IN ('NOT_STARTED', 'RUNNING', 'COMPLETED', 'CANCELLED')),
    notes               VARCHAR(500),

    CONSTRAINT pk_trips PRIMARY KEY (trip_id),
    CONSTRAINT uq_trips_schedule_date UNIQUE (schedule_id, service_date),
    CONSTRAINT fk_trips_schedule FOREIGN KEY (schedule_id)
        REFERENCES bus_schedules(schedule_id),
    CONSTRAINT ck_trips_time CHECK (
        departed_at IS NULL OR ended_at IS NULL OR ended_at >= departed_at
    )
);

CREATE TABLE IF NOT EXISTS stop_arrival_estimates (
    estimate_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trip_id             INTEGER NOT NULL,
    route_stop_id       INTEGER NOT NULL,
    estimated_arrival_at TIMESTAMPTZ NOT NULL,
    actual_arrival_at   TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stop_arrival_estimates PRIMARY KEY (estimate_id),
    CONSTRAINT uq_stop_arrival_trip_route_stop UNIQUE (trip_id, route_stop_id),
    CONSTRAINT fk_stop_arrival_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id) ON DELETE CASCADE,
    CONSTRAINT fk_stop_arrival_route_stop FOREIGN KEY (route_stop_id)
        REFERENCES route_stops(route_stop_id)
);

-- =====================================================================
-- SECTION 4: REGISTRATION, TICKETS AND TRAVEL
-- =====================================================================

CREATE TABLE IF NOT EXISTS route_registrations (
    registration_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code        VARCHAR(20) NOT NULL,
    route_id            INTEGER NOT NULL,
    boarding_route_stop_id INTEGER,
    alighting_route_stop_id INTEGER,
    registered_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_date      DATE,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'APPROVED', 'CANCELLED')),
    previous_registration_id INTEGER,
    cancellation_reason VARCHAR(500),
    approved_by_user_id INTEGER,
    approved_at         TIMESTAMPTZ,

    CONSTRAINT pk_route_registrations PRIMARY KEY (registration_id),
    CONSTRAINT fk_registrations_student FOREIGN KEY (student_code)
        REFERENCES students(student_code),
    CONSTRAINT fk_registrations_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id),
    CONSTRAINT fk_registrations_boarding_route_stop FOREIGN KEY (route_id, boarding_route_stop_id)
        REFERENCES route_stops(route_id, route_stop_id),
    CONSTRAINT fk_registrations_alighting_route_stop FOREIGN KEY (route_id, alighting_route_stop_id)
        REFERENCES route_stops(route_id, route_stop_id),
    CONSTRAINT fk_registrations_previous FOREIGN KEY (previous_registration_id)
        REFERENCES route_registrations(registration_id),
    CONSTRAINT fk_registrations_approved_by FOREIGN KEY (approved_by_user_id)
        REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS travel_history (
    travel_history_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code        VARCHAR(20) NOT NULL,
    trip_id             INTEGER NOT NULL,
    registration_id     INTEGER,
    ticket_id           INTEGER,
    boarding_route_stop_id INTEGER,
    alighting_route_stop_id INTEGER,
    boarded_at          TIMESTAMPTZ,
    alighted_at         TIMESTAMPTZ,
    confirmation_method VARCHAR(20)
                        CHECK (confirmation_method IN ('QR_SCAN', 'MANUAL', 'SYSTEM')),
    confirmed_by_staff_id INTEGER,

    CONSTRAINT pk_travel_history PRIMARY KEY (travel_history_id),
    CONSTRAINT fk_travel_history_student FOREIGN KEY (student_code)
        REFERENCES students(student_code),
    CONSTRAINT fk_travel_history_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id),
    CONSTRAINT fk_travel_history_registration FOREIGN KEY (registration_id)
        REFERENCES route_registrations(registration_id),
    CONSTRAINT fk_travel_history_boarding_route_stop FOREIGN KEY (boarding_route_stop_id)
        REFERENCES route_stops(route_stop_id),
    CONSTRAINT fk_travel_history_alighting_route_stop FOREIGN KEY (alighting_route_stop_id)
        REFERENCES route_stops(route_stop_id),
    CONSTRAINT fk_travel_history_conductor FOREIGN KEY (confirmed_by_staff_id)
        REFERENCES staff_profiles(staff_id),
    CONSTRAINT ck_travel_history_time CHECK (
        boarded_at IS NULL OR alighted_at IS NULL OR alighted_at >= boarded_at
    )
);

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_type         VARCHAR(10) NOT NULL CHECK (ticket_type IN ('SINGLE', 'MONTHLY')),
    student_code        VARCHAR(20) NOT NULL,
    route_id            INTEGER NOT NULL,
    boarding_route_stop_id INTEGER,
    alighting_route_stop_id INTEGER,
    effective_month     INTEGER CHECK (effective_month IS NULL OR effective_month BETWEEN 1 AND 12),
    effective_year      INTEGER CHECK (effective_year IS NULL OR effective_year >= 2000),
    valid_from          TIMESTAMPTZ NOT NULL,
    expires_at          TIMESTAMPTZ NOT NULL,
    fare_amount         NUMERIC(12,0) NOT NULL CHECK (fare_amount >= 0),
    qr_code             VARCHAR(255),
    purchased_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_on_trip_id     INTEGER,
    last_scanned_at     TIMESTAMPTZ,
    scanned_by_staff_id INTEGER,
    scans_today         INTEGER NOT NULL DEFAULT 0 CHECK (scans_today >= 0),
    status              VARCHAR(20) NOT NULL DEFAULT 'UNUSED'
                        CHECK (status IN ('UNUSED', 'ACTIVE', 'USED', 'EXPIRED', 'CANCELLED')),

    CONSTRAINT pk_tickets PRIMARY KEY (ticket_id),
    CONSTRAINT uq_tickets_qr_code UNIQUE (qr_code),
    CONSTRAINT fk_tickets_student FOREIGN KEY (student_code)
        REFERENCES students(student_code),
    CONSTRAINT fk_tickets_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id),
    CONSTRAINT fk_tickets_boarding_route_stop FOREIGN KEY (route_id, boarding_route_stop_id)
        REFERENCES route_stops(route_id, route_stop_id),
    CONSTRAINT fk_tickets_alighting_route_stop FOREIGN KEY (route_id, alighting_route_stop_id)
        REFERENCES route_stops(route_id, route_stop_id),
    CONSTRAINT fk_tickets_used_trip FOREIGN KEY (used_on_trip_id)
        REFERENCES trips(trip_id),
    CONSTRAINT fk_tickets_scanned_by FOREIGN KEY (scanned_by_staff_id)
        REFERENCES staff_profiles(staff_id),
    CONSTRAINT ck_tickets_validity CHECK (expires_at > valid_from),
    CONSTRAINT ck_tickets_type_fields CHECK (
        (ticket_type = 'MONTHLY' AND effective_month IS NOT NULL AND effective_year IS NOT NULL
            AND status IN ('ACTIVE', 'EXPIRED', 'CANCELLED') AND used_on_trip_id IS NULL)
        OR
        (ticket_type = 'SINGLE' AND effective_month IS NULL AND effective_year IS NULL
            AND status IN ('UNUSED', 'USED', 'EXPIRED', 'CANCELLED'))
    )
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_travel_history_ticket'
    ) THEN
        ALTER TABLE travel_history
            ADD CONSTRAINT fk_travel_history_ticket FOREIGN KEY (ticket_id)
            REFERENCES tickets(ticket_id);
    END IF;
END;
$$;

-- =====================================================================
-- SECTION 5: PAYMENTS AND FARES
-- =====================================================================

CREATE TABLE IF NOT EXISTS payments (
    payment_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id           INTEGER NOT NULL,
    amount              NUMERIC(12,0) NOT NULL CHECK (amount >= 0),
    method              VARCHAR(20) NOT NULL
                        CHECK (method IN ('CASH', 'BANK_TRANSFER', 'E_WALLET', 'CARD')),
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
    transaction_code    VARCHAR(100),
    invoice_number      VARCHAR(100),
    invoice_issued_at   TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes               VARCHAR(500),

    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT uq_payments_transaction_code UNIQUE (transaction_code),
    CONSTRAINT uq_payments_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_payments_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets(ticket_id)
);

CREATE TABLE IF NOT EXISTS fares (
    fare_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_id            INTEGER NOT NULL,
    fare_type           VARCHAR(10) NOT NULL CHECK (fare_type IN ('SINGLE', 'MONTHLY')),
    amount              NUMERIC(12,0) NOT NULL CHECK (amount >= 0),
    effective_from      DATE NOT NULL,
    effective_until     DATE,
    adjusted_by_user_id INTEGER,
    notes               VARCHAR(500),

    CONSTRAINT pk_fares PRIMARY KEY (fare_id),
    CONSTRAINT uq_fares_route_type_start UNIQUE (route_id, fare_type, effective_from),
    CONSTRAINT fk_fares_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id),
    CONSTRAINT fk_fares_adjusted_by FOREIGN KEY (adjusted_by_user_id)
        REFERENCES users(user_id),
    CONSTRAINT ck_fares_effective_range CHECK (
        effective_until IS NULL OR effective_until >= effective_from
    )
);

-- =====================================================================
-- SECTION 6: RATINGS, CASES AND COMMUNICATIONS
-- =====================================================================

CREATE TABLE IF NOT EXISTS driver_ratings (
    driver_rating_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_code        VARCHAR(20) NOT NULL,
    driver_staff_id     INTEGER NOT NULL,
    trip_id             INTEGER,
    stars               INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
    comment             VARCHAR(1000),
    rated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_driver_ratings PRIMARY KEY (driver_rating_id),
    CONSTRAINT uq_driver_ratings_student_trip UNIQUE (student_code, trip_id),
    CONSTRAINT fk_driver_ratings_student FOREIGN KEY (student_code)
        REFERENCES students(student_code),
    CONSTRAINT fk_driver_ratings_driver FOREIGN KEY (driver_staff_id)
        REFERENCES staff_profiles(staff_id),
    CONSTRAINT fk_driver_ratings_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id)
);

CREATE TABLE IF NOT EXISTS cases (
    case_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_type           VARCHAR(20) NOT NULL
                        CHECK (case_type IN ('FEEDBACK', 'COMPLAINT', 'VIOLATION', 'SUPPORT', 'LOST_ITEM', 'INCIDENT')),
    submitted_by_user_id INTEGER NOT NULL,
    subject_user_id     INTEGER,
    route_id            INTEGER,
    trip_id             INTEGER,
    ticket_id           INTEGER,
    category            VARCHAR(50),
    title               VARCHAR(200),
    content             VARCHAR(2000) NOT NULL,
    rating              INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    priority            VARCHAR(10) NOT NULL DEFAULT 'NORMAL'
                        CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    status              VARCHAR(20) NOT NULL DEFAULT 'NEW'
                        CHECK (status IN ('NEW', 'OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'CLOSED', 'FOUND', 'NOT_FOUND')),
    resolution          VARCHAR(2000),
    handled_by_user_id  INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ,
    closed_at           TIMESTAMPTZ,

    CONSTRAINT pk_cases PRIMARY KEY (case_id),
    CONSTRAINT fk_cases_submitter FOREIGN KEY (submitted_by_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_cases_subject FOREIGN KEY (subject_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_cases_route FOREIGN KEY (route_id)
        REFERENCES routes(route_id),
    CONSTRAINT fk_cases_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id),
    CONSTRAINT fk_cases_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets(ticket_id),
    CONSTRAINT fk_cases_handler FOREIGN KEY (handled_by_user_id)
        REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS communications (
    communication_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    communication_kind  VARCHAR(20) NOT NULL
                        CHECK (communication_kind IN ('NOTIFICATION', 'MESSAGE')),
    recipient_user_id   INTEGER,
    sender_user_id      INTEGER,
    trip_id             INTEGER,
    case_id             INTEGER,
    title               VARCHAR(200),
    content             VARCHAR(2000) NOT NULL,
    communication_type  VARCHAR(20) NOT NULL DEFAULT 'SYSTEM'
                        CHECK (communication_type IN ('SYSTEM', 'TRIP', 'PAYMENT', 'CASE', 'ALERT', 'DIRECT')),
    is_read             BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at             TIMESTAMPTZ,

    CONSTRAINT pk_communications PRIMARY KEY (communication_id),
    CONSTRAINT fk_communications_recipient FOREIGN KEY (recipient_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_communications_sender FOREIGN KEY (sender_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_communications_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id),
    CONSTRAINT fk_communications_case FOREIGN KEY (case_id)
        REFERENCES cases(case_id),
    CONSTRAINT ck_communications_message_recipient CHECK (
        communication_kind <> 'MESSAGE' OR recipient_user_id IS NOT NULL
    )
);

-- =====================================================================
-- SECTION 7: LOCATION, AI AND AUDIT
-- =====================================================================

CREATE TABLE IF NOT EXISTS vehicle_locations (
    vehicle_location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_id              INTEGER,
    trip_id             INTEGER,
    longitude           NUMERIC(11,8) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    latitude            NUMERIC(10,8) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    speed_kmh           NUMERIC(5,2) CHECK (speed_kmh IS NULL OR speed_kmh >= 0),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_vehicle_locations PRIMARY KEY (vehicle_location_id),
    CONSTRAINT fk_vehicle_locations_bus FOREIGN KEY (bus_id)
        REFERENCES buses(bus_id),
    CONSTRAINT fk_vehicle_locations_trip FOREIGN KEY (trip_id)
        REFERENCES trips(trip_id),
    CONSTRAINT ck_vehicle_locations_target CHECK (
        (bus_id IS NOT NULL AND trip_id IS NULL)
        OR
        (bus_id IS NULL AND trip_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS ai_chat_history (
    chat_history_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             INTEGER NOT NULL,
    chat_session_id     UUID NOT NULL DEFAULT gen_random_uuid(),
    message_role        VARCHAR(10) NOT NULL CHECK (message_role IN ('USER', 'AI')),
    content             TEXT NOT NULL,
    advisory_type       VARCHAR(20)
                        CHECK (advisory_type IN ('ROUTE_SUGGESTION', 'FARE_LOOKUP', 'SCHEDULE_LOOKUP', 'OTHER')),
    sent_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ai_chat_history PRIMARY KEY (chat_history_id),
    CONSTRAINT fk_ai_chat_history_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    performed_by_user_id INTEGER,
    action              VARCHAR(50) NOT NULL,
    affected_table      VARCHAR(50),
    affected_record_id  VARCHAR(50),
    old_values          JSONB,
    new_values          JSONB,
    ip_address          VARCHAR(45),
    notes               VARCHAR(500),
    performed_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT fk_audit_logs_performer FOREIGN KEY (performed_by_user_id)
        REFERENCES users(user_id)
);

-- =====================================================================
-- SECTION 8: ROLE VALIDATION TRIGGERS
-- =====================================================================

CREATE OR REPLACE FUNCTION fn_validate_student_profile_role()
RETURNS TRIGGER AS $$
DECLARE
    actual_role VARCHAR(20);
BEGIN
    SELECT role INTO actual_role
    FROM users
    WHERE user_id = NEW.user_id;

    IF actual_role <> 'STUDENT' THEN
        RAISE EXCEPTION 'students.user_id must reference a STUDENT user, got %', actual_role;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_student_profile_role ON students;

CREATE TRIGGER trg_validate_student_profile_role
BEFORE INSERT OR UPDATE OF user_id ON students
FOR EACH ROW EXECUTE FUNCTION fn_validate_student_profile_role();

CREATE OR REPLACE FUNCTION fn_validate_staff_profile_role()
RETURNS TRIGGER AS $$
DECLARE
    actual_role VARCHAR(20);
BEGIN
    SELECT role INTO actual_role
    FROM users
    WHERE user_id = NEW.user_id;

    IF actual_role NOT IN ('DRIVER', 'CONDUCTOR', 'DISPATCHER') THEN
        RAISE EXCEPTION 'staff_profiles.user_id must reference staff user, got %', actual_role;
    END IF;

    IF actual_role = 'DRIVER' AND NEW.license_number IS NULL THEN
        RAISE EXCEPTION 'DRIVER staff profile requires license_number';
    END IF;

    IF actual_role IN ('CONDUCTOR', 'DISPATCHER') AND NEW.employee_code IS NULL THEN
        RAISE EXCEPTION 'CONDUCTOR/DISPATCHER staff profile requires employee_code';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_staff_profile_role ON staff_profiles;

CREATE TRIGGER trg_validate_staff_profile_role
BEFORE INSERT OR UPDATE OF user_id, employee_code, license_number ON staff_profiles
FOR EACH ROW EXECUTE FUNCTION fn_validate_staff_profile_role();

CREATE OR REPLACE FUNCTION fn_validate_schedule_staff_roles()
RETURNS TRIGGER AS $$
DECLARE
    driver_role VARCHAR(20);
    conductor_role VARCHAR(20);
BEGIN
    SELECT u.role INTO driver_role
    FROM staff_profiles sp
    JOIN users u ON u.user_id = sp.user_id
    WHERE sp.staff_id = NEW.driver_staff_id;

    IF driver_role <> 'DRIVER' THEN
        RAISE EXCEPTION 'bus_schedules.driver_staff_id must reference DRIVER staff';
    END IF;

    IF NEW.conductor_staff_id IS NOT NULL THEN
        SELECT u.role INTO conductor_role
        FROM staff_profiles sp
        JOIN users u ON u.user_id = sp.user_id
        WHERE sp.staff_id = NEW.conductor_staff_id;

        IF conductor_role <> 'CONDUCTOR' THEN
            RAISE EXCEPTION 'bus_schedules.conductor_staff_id must reference CONDUCTOR staff';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_schedule_staff_roles ON bus_schedules;

CREATE TRIGGER trg_validate_schedule_staff_roles
BEFORE INSERT OR UPDATE OF driver_staff_id, conductor_staff_id ON bus_schedules
FOR EACH ROW EXECUTE FUNCTION fn_validate_schedule_staff_roles();

CREATE OR REPLACE FUNCTION fn_validate_driver_rating_role()
RETURNS TRIGGER AS $$
DECLARE
    actual_role VARCHAR(20);
BEGIN
    SELECT u.role INTO actual_role
    FROM staff_profiles sp
    JOIN users u ON u.user_id = sp.user_id
    WHERE sp.staff_id = NEW.driver_staff_id;

    IF actual_role <> 'DRIVER' THEN
        RAISE EXCEPTION 'driver_ratings.driver_staff_id must reference DRIVER staff';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_driver_rating_role ON driver_ratings;

CREATE TRIGGER trg_validate_driver_rating_role
BEFORE INSERT OR UPDATE OF driver_staff_id ON driver_ratings
FOR EACH ROW EXECUTE FUNCTION fn_validate_driver_rating_role();

-- =====================================================================
-- SECTION 9: QUERY PERFORMANCE INDEXES
-- =====================================================================

CREATE INDEX IF NOT EXISTS ix_users_role
    ON users(role);
CREATE INDEX IF NOT EXISTS ix_users_status
    ON users(status);

CREATE INDEX IF NOT EXISTS ix_login_sessions_user_active
    ON login_sessions(user_id, is_active)
    INCLUDE (expires_at, token_hash);

CREATE INDEX IF NOT EXISTS ix_verification_codes_active
    ON verification_codes(email, purpose, expires_at DESC)
    WHERE consumed_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_user_auth_providers_user
    ON user_auth_providers(user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_user
    ON student_verifications(user_id)
    WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_verifications_current_student_code
    ON student_verifications(student_code)
    WHERE is_current AND status IN ('PENDING_REVIEW', 'VERIFIED', 'RESUBMISSION_REQUIRED');

CREATE INDEX IF NOT EXISTS ix_student_verifications_status
    ON student_verifications(status, submitted_at DESC);

CREATE INDEX IF NOT EXISTS ix_staff_profiles_user
    ON staff_profiles(user_id);

CREATE INDEX IF NOT EXISTS ix_route_stops_route_order
    ON route_stops(route_id, stop_order);

CREATE INDEX IF NOT EXISTS ix_bus_schedules_weekday
    ON bus_schedules(weekday_number, departure_time);

CREATE INDEX IF NOT EXISTS ix_trips_service_date
    ON trips(service_date);
CREATE INDEX IF NOT EXISTS ix_trips_status
    ON trips(status);

CREATE INDEX IF NOT EXISTS ix_arrival_estimates_trip_stop
    ON stop_arrival_estimates(trip_id, route_stop_id)
    INCLUDE (estimated_arrival_at);

CREATE UNIQUE INDEX IF NOT EXISTS uq_registrations_one_pending_per_student
    ON route_registrations(student_code)
    WHERE status = 'PENDING';

CREATE UNIQUE INDEX IF NOT EXISTS uq_registrations_one_approved_per_student
    ON route_registrations(student_code)
    WHERE status = 'APPROVED';

CREATE INDEX IF NOT EXISTS ix_travel_history_student
    ON travel_history(student_code, boarded_at DESC);
CREATE INDEX IF NOT EXISTS ix_travel_history_trip
    ON travel_history(trip_id);

CREATE INDEX IF NOT EXISTS ix_tickets_student_purchase
    ON tickets(student_code, purchased_at DESC);
CREATE INDEX IF NOT EXISTS ix_tickets_status_expiration
    ON tickets(status, expires_at)
    INCLUDE (student_code, route_id, qr_code);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tickets_active_monthly_pass
    ON tickets(student_code, route_id, effective_year, effective_month)
    WHERE ticket_type = 'MONTHLY' AND status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS ix_payments_ticket
    ON payments(ticket_id);
CREATE INDEX IF NOT EXISTS ix_payments_status
    ON payments(status);

CREATE INDEX IF NOT EXISTS ix_fares_route_type_dates
    ON fares(route_id, fare_type, effective_from DESC, effective_until);

CREATE INDEX IF NOT EXISTS ix_driver_ratings_driver
    ON driver_ratings(driver_staff_id);

CREATE INDEX IF NOT EXISTS ix_cases_submitter
    ON cases(submitted_by_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_cases_status
    ON cases(status, priority);
CREATE INDEX IF NOT EXISTS ix_cases_type
    ON cases(case_type);

CREATE INDEX IF NOT EXISTS ix_communications_recipient_read
    ON communications(recipient_user_id, is_read, sent_at DESC);
CREATE INDEX IF NOT EXISTS ix_communications_case
    ON communications(case_id);

CREATE INDEX IF NOT EXISTS ix_vehicle_locations_bus_time
    ON vehicle_locations(bus_id, updated_at DESC)
    WHERE bus_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_vehicle_locations_trip_time
    ON vehicle_locations(trip_id, updated_at DESC)
    WHERE trip_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ai_chat_user_time
    ON ai_chat_history(user_id, sent_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_logs_performer_time
    ON audit_logs(performed_by_user_id, performed_at DESC);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action_time
    ON audit_logs(action, performed_at DESC);

COMMIT;
