spring.application.name=bussvdn-backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=BusSVDN;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.time-zone=Asia/Ho_Chi_Minh

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
